.\"                                      Hey, EMACS: -*- nroff -*-
.TH VSID 1 "August 18, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
vsid \- Play Commdore 64 SID music files
.SH SYNOPSIS
.B vsid
.RI musicfile.sid
.SH DESCRIPTION
.B vsid
passes a Commodore 64 SID music file to the VICE x64 emulator, which
then plays the default song on /dev/dsp.
.SH SEE ALSO
.BR x64 (1),
.BR sidplay (1).
.SH AUTHOR
This manual page was written by Zed Pobre <zed@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
