#!/bin/sh

EXE="wolf3d"
ROM=$1
NAME=`basename ${0}`
LOG_FILE=/var/log/${NAME}.log

# set DEBUG="1" to debug
DEBUG="1"

if [ "${DEBUG}" != "0" ];
then
	echo "*** ${NAME} `date` ***" > ${LOG_FILE}; cat /proc/bus/input/devices >> ${LOG_FILE}; cat $0 >> ${LOG_FILE}; set -x; exec >> ${LOG_FILE} 2>&1
fi

export DISPLAY=0
export TERM="linux"
export HOME="/root"
export SDL_BCMFB_ACCEL=0
export SDL_VIDEODRIVER="bcmfb"
export SDL_AUDIODRIVER="alsa"
export SDL_DEBUG=${DEBUG}

fbset -depth 16

cd /usr/bin
/usr/bin/${EXE} -basedir /usr/share/games/wolf3d

exit 0
