#!/bin/sh

EXE="pcsx"
ROM=$1
NAME=`basename ${0}`
LOG_FILE=/var/log/${EXE}.log

# set DEBUG="1" to debug
DEBUG="1"

if [ "${DEBUG}" != "0" ];
then
	echo "*** ${NAME} `date` ***" > ${LOG_FILE}; cat /proc/bus/input/devices >> ${LOG_FILE}; cat $0 >> ${LOG_FILE}; set -x; exec >> ${LOG_FILE} 2>&1
fi

export DISPLAY=0
export TERM="linux"
export HOME="/root"
export SDL_VIDEODRIVER="bcmfb"
export SDL_BCMFB_ACCEL=0
export SDL_AUDIODRIVER="alsa"
export SDL_DEBUG=${DEBUG}
export SDL_FBACCEL=0
export SDL_VIDEO_YUV_HWACCEL=0
#export SDL_NOMOUSE=1

fbset -depth 16

if [ `echo ${ROM} | grep -c ".exe"` != 0 ]; then
	/usr/games/${EXE} "${ROM}"
else
	/usr/games/${EXE} -cdfile "${ROM}"
fi

exit 0
