#!/bin/sh

EXE="snes9x-sdl"
ROM=$1
NAME=`basename ${0}`
LOG_FILE=/var/log/${EXE}.log

# set DEBUG="1" to debug
DEBUG="1"

if [ "${DEBUG}" != "0" ];
then
	echo "*** ${NAME} `date` ***" > ${LOG_FILE}; cat /proc/bus/input/devices >> ${LOG_FILE}; cat $0 >> ${LOG_FILE}; set -x; exec >> ${LOG_FILE} 2>&1
fi

export DISPLAY=:0
export TERM="linux"
export HOME="/root"
export SDL_VIDEO_YUV_DIRECT=1
export SDL_VIDEODRIVER="fbcon"
export SDL_AUDIODRIVER="alsa"
export SDL_NOMOUSE=1
export SDL_DEBUG=${DEBUG}


if [ "${ROM}" != "" ];
then
	if [ "${DEBUG}" != "0" ];
	then
		/usr/bin/${EXE} -displaykeypress -v3 "${ROM}"
	else
		/usr/bin/${EXE} -v3 "${ROM}"
	fi
else
	echo "${NAME}: no rom found! - exit"
	exit 1
fi

exit 0
